.TH "Actor" 3 "Tue Dec 15 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Actor \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Actor\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBattack\fP"
.br
.ti -1c
.RI "int \fBhealth\fP"
.br
.ti -1c
.RI "string \fBfullName\fP"
.br
.ti -1c
.RI "string \fBclassSelected\fP"
.br
.ti -1c
.RI "int \fBenergy\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int Actor::attack"

.SS "string Actor::classSelected"

.SS "int Actor::energy"

.SS "string Actor::fullName"

.SS "int Actor::health"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
