.TH "Bonus" 3 "Tue Dec 15 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bonus \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BonusPt\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBonus\fP ()"
.br
.ti -1c
.RI "\fB~Bonus\fP ()"
.br
.ti -1c
.RI "void \fBsetNumber\fP ()"
.br
.ti -1c
.RI "int \fBgetNumber\fP () const "
.br
.ti -1c
.RI "int \fBgetBonus\fP () const "
.br
.ti -1c
.RI "int \fBgetMBonus\fP () const "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBBonH\fP ()"
.br
.ti -1c
.RI "static int \fBAI_Bns\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Bonus::Bonus ()"

.SS "Bonus::~Bonus ()"

.SH "Member Function Documentation"
.PP 
.SS "int Bonus::AI_Bns ()\fC [static]\fP"

.SS "int Bonus::BonH ()\fC [static]\fP"

.SS "int Bonus::getBonus () const\fC [inline]\fP"

.SS "int Bonus::getMBonus () const\fC [inline]\fP"

.SS "int Bonus::getNumber () const\fC [inline]\fP"

.SS "void Bonus::setNumber ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
