.TH "Creator.cpp" 3 "Tue Dec 15 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Creator.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'Creator\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
