.TH "Creator" 3 "Tue Dec 15 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Creator \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Creator\&.h>\fP
.PP
Inherits \fBDeveloper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCreator\fP ()"
.br
.ti -1c
.RI "\fB~Creator\fP ()"
.br
.ti -1c
.RI "void \fBsetDay\fP (int)"
.br
.ti -1c
.RI "void \fBsetLevel\fP (int)"
.br
.ti -1c
.RI "int \fBgetDay\fP ()"
.br
.ti -1c
.RI "int \fBgetLevel\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Creator::Creator ()"

.SS "Creator::~Creator ()"

.SH "Member Function Documentation"
.PP 
.SS "int Creator::getDay ()"

.SS "int Creator::getLevel ()"

.SS "void Creator::setDay (int d)"

.SS "void Creator::setLevel (int l)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
