.TH "Developer" 3 "Tue Dec 15 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Developer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Developer\&.h>\fP
.PP
Inherited by \fBCreator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDeveloper\fP ()"
.br
.ti -1c
.RI "\fBDeveloper\fP (string, int, string)"
.br
.ti -1c
.RI "\fBDeveloper\fP (const \fBDeveloper\fP &orig)"
.br
.ti -1c
.RI "\fB~Developer\fP ()"
.br
.ti -1c
.RI "void \fBsetName\fP (string)"
.br
.ti -1c
.RI "void \fBsetNumber\fP (int)"
.br
.ti -1c
.RI "void \fBsetDate\fP (string)"
.br
.ti -1c
.RI "string \fBgetName\fP ()"
.br
.ti -1c
.RI "int \fBgetNumber\fP ()"
.br
.ti -1c
.RI "string \fBgetDate\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string \fBdate\fP"
.br
.ti -1c
.RI "\fBmy_NumberT\fP< int > \fBnumber\fP"
.br
.ti -1c
.RI "\fBmy_NumberT\fP< float > \fBsalary\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Developer::Developer ()"

.SS "Developer::Developer (string n, int num, string d)"

.SS "Developer::Developer (const \fBDeveloper\fP & orig)"

.SS "Developer::~Developer ()"

.SH "Member Function Documentation"
.PP 
.SS "string Developer::getDate ()"

.SS "string Developer::getName ()"

.SS "int Developer::getNumber ()"

.SS "void Developer::setDate (string d)"

.SS "void Developer::setName (string n)"

.SS "void Developer::setNumber (int num)"

.SH "Member Data Documentation"
.PP 
.SS "string Developer::date\fC [protected]\fP"

.SS "string Developer::name\fC [protected]\fP"

.SS "\fBmy_NumberT\fP<int> Developer::number\fC [protected]\fP"

.SS "\fBmy_NumberT\fP<float> Developer::salary\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
