.TH "GameDate" 3 "Tue Dec 15 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameDate \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GameDate\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGameDate\fP ()"
.br
.ti -1c
.RI "\fBGameDate\fP (const \fBGameDate\fP &obj)"
.br
.ti -1c
.RI "\fB~GameDate\fP ()"
.br
.ti -1c
.RI "void \fBsetMonth\fP (int)"
.br
.ti -1c
.RI "void \fBsetDay\fP (int)"
.br
.ti -1c
.RI "void \fBsetYear\fP (int)"
.br
.ti -1c
.RI "int \fBgetDay\fP ()"
.br
.ti -1c
.RI "int \fBgetMonth\fP ()"
.br
.ti -1c
.RI "int \fBgetYear\fP ()"
.br
.ti -1c
.RI "void \fBprint\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBMDY\fP (\fBGameDate\fP *)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GameDate::GameDate ()"

.SS "GameDate::GameDate (const \fBGameDate\fP & obj)"

.SS "GameDate::~GameDate ()"

.SH "Member Function Documentation"
.PP 
.SS "int GameDate::getDay ()"

.SS "int GameDate::getMonth ()"

.SS "int GameDate::getYear ()"

.SS "void GameDate::MDY (\fBGameDate\fP * date)\fC [static]\fP"

.SS "void GameDate::print ()"

.SS "void GameDate::setDay (int d)"

.SS "void GameDate::setMonth (int m)"

.SS "void GameDate::setYear (int y)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
