.TH "MilushYanev_Project2/html/search/all_8.js" 3 "Tue Dec 15 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MilushYanev_Project2/html/search/all_8.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.ti -1c
.RI "\fBmain\fP \fBcpp\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBmain\fP cpp"

.PP
Definition at line 3 of file all_8\&.js\&.
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['load',['load',['\&.\&./_actor_8h\&.html#af3dc1f4eaeaabc4cb2741c991bc47f3d',1,'load(GameDate &amp;date, Actor &amp;player, Actor &amp;enemy):&#160
.fi
.PP
Definition at line 1 of file all_8\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
