.TH "MilushYanev_Project2/html/search/all_6.js" 3 "Tue Dec 15 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MilushYanev_Project2/html/search/all_6.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.ti -1c
.RI "\fBmain\fP \fBcpp\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBmain\fP cpp"

.PP
Definition at line 6 of file all_6\&.js\&.
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['gamedate',['GameDate',['\&.\&./class_game_date\&.html',1,'GameDate'],['\&.\&./class_game_date\&.html#ab0e226510ab6260cd438add7ad3b0e6f',1,'GameDate::GameDate()'],['\&.\&./class_game_date\&.html#ac1ae5749ab973a55a85a1fd69e04e003',1,'GameDate::GameDate(const GameDate &amp;obj)']]],
  ['gamedate_2ecpp',['GameDate\&.cpp',['\&.\&./_game_date_8cpp\&.html',1,'']]],
  ['gamedate_2eh',['GameDate\&.h',['\&.\&./_game_date_8h\&.html',1,'']]],
  ['gamemanager',['gameManager',['\&.\&./_actor_8h\&.html#a1fa62b46e875fff4cb5f5ea66f93a671',1,'gameManager():&#160
.fi
.PP
Definition at line 1 of file all_6\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
