.TH "MilushYanev_Project2/html/search/all_3.js" 3 "Tue Dec 15 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MilushYanev_Project2/html/search/all_3.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['date',['date',['\&.\&./class_developer\&.html#ad157908ba8bd6ac6b16c8e28502953be',1,'Developer']]],
  ['developer',['Developer',['\&.\&./class_developer\&.html',1,'Developer'],['\&.\&./class_developer\&.html#a1acf937b03598b68b93c010bfc90f702',1,'Developer::Developer()'],['\&.\&./class_developer\&.html#a24c1cde234cb63807179251c8516f69e',1,'Developer::Developer(string, int, string)'],['\&.\&./class_developer\&.html#a70d27630049849deaf3fbc8fab301908',1,'Developer::Developer(const Developer &amp;orig)']]],
  ['developer_2ecpp',['Developer\&.cpp',['\&.\&./_developer_8cpp\&.html',1,'']]],
  ['developer_2eh',['Developer\&.h',['\&.\&./_developer_8h\&.html',1,'']]]
]
.fi
.PP
Definition at line 1 of file all_3\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
