.TH "MilushYanev_Project2/html/annotated_dup.js" 3 "Tue Dec 15 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MilushYanev_Project2/html/annotated_dup.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBannotated_dup\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var annotated_dup"
\fBInitial value:\fP
.PP
.nf
=
[
    [ "Actor", "struct_actor\&.html", "struct_actor" ],
    [ "Bonus", "class_bonus\&.html", "class_bonus" ],
    [ "Creator", "class_creator\&.html", "class_creator" ],
    [ "Developer", "class_developer\&.html", "class_developer" ],
    [ "GameDate", "class_game_date\&.html", "class_game_date" ],
    [ "my_NumberT", "classmy___number_t\&.html", "classmy___number_t" ]
]
.fi
.PP
Definition at line 1 of file annotated_dup\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
