.TH "MilushYanev_Project2/BonusPt.cpp" 3 "Tue Dec 15 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MilushYanev_Project2/BonusPt.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include 'BonusPt\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
