.TH "MilushYanev_Project2/html/classmy___number_t.js" 3 "Tue Dec 15 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MilushYanev_Project2/html/classmy___number_t.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBclassmy___number_t\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var classmy___number_t"
\fBInitial value:\fP
.PP
.nf
=
[
    [ "my_NumberT", "classmy___number_t\&.html#aae9f7035af1da340e063e9618dc642a2", null ],
    [ "my_NumberT", "classmy___number_t\&.html#a711259667444161bbdc149533e8dd2b8", null ],
    [ "getValue", "classmy___number_t\&.html#ac987528d323d8a2ed013a200ddb13a5f", null ],
    [ "setValue", "classmy___number_t\&.html#a0df005c28c1b133efdf67283126fae17", null ]
]
.fi
.PP
Definition at line 1 of file classmy___number_t\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
