.TH "MilushYanev_Project2/html/search/classes_0.js" 3 "Tue Dec 15 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MilushYanev_Project2/html/search/classes_0.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['actor',['Actor',['\&.\&./struct_actor\&.html',1,'']]]
]
.fi
.PP
Definition at line 1 of file classes_0\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
