.TH "MilushYanev_Project2/html/class_game_date.js" 3 "Tue Dec 15 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MilushYanev_Project2/html/class_game_date.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBclass_game_date\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var class_game_date"
\fBInitial value:\fP
.PP
.nf
=
[
    [ "GameDate", "class_game_date\&.html#ab0e226510ab6260cd438add7ad3b0e6f", null ],
    [ "GameDate", "class_game_date\&.html#ac1ae5749ab973a55a85a1fd69e04e003", null ],
    [ "~GameDate", "class_game_date\&.html#a036e058a9f70791d229de1568e1a2c73", null ],
    [ "getDay", "class_game_date\&.html#aa5f51d52c16e608253fd4c2762a1dfbb", null ],
    [ "getMonth", "class_game_date\&.html#a2b8fba33da7e4820587a2e6ccc9411e0", null ],
    [ "getYear", "class_game_date\&.html#ac996cd8d1fbd5a4ad9ede22a6b9aa7aa", null ],
    [ "print", "class_game_date\&.html#ae0829c804c22c72d1fe34080aed5cea3", null ],
    [ "setDay", "class_game_date\&.html#aba5c6ab5a4f050ceb431fbcd037009d3", null ],
    [ "setMonth", "class_game_date\&.html#a55608e9a69e32403ae008291681bbf59", null ],
    [ "setYear", "class_game_date\&.html#adcaba92c4db1fa259a5d8ae9704064e5", null ]
]
.fi
.PP
Definition at line 1 of file class_game_date\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
