.TH "MilushYanev_Project2/html/class_developer.js" 3 "Tue Dec 15 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MilushYanev_Project2/html/class_developer.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBclass_developer\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var class_developer"
\fBInitial value:\fP
.PP
.nf
=
[
    [ "Developer", "class_developer\&.html#a1acf937b03598b68b93c010bfc90f702", null ],
    [ "Developer", "class_developer\&.html#a24c1cde234cb63807179251c8516f69e", null ],
    [ "Developer", "class_developer\&.html#a70d27630049849deaf3fbc8fab301908", null ],
    [ "~Developer", "class_developer\&.html#a3a358890cdc55c7c473bbe0865ca0dde", null ],
    [ "getDate", "class_developer\&.html#a5ab8342af9b6352324787b66a1035c69", null ],
    [ "getName", "class_developer\&.html#abcaa88f55cd1dbd58daf281f8b504172", null ],
    [ "getNumber", "class_developer\&.html#ab1e964805d449751217f40e210596fc3", null ],
    [ "setDate", "class_developer\&.html#aebac796aa948255e4ca15c8fbbc0d010", null ],
    [ "setName", "class_developer\&.html#aed0b441a49c60fcfbcdeb730bc6efb79", null ],
    [ "setNumber", "class_developer\&.html#afa96e363d27b88c0c54ebffadef4f728", null ],
    [ "date", "class_developer\&.html#ad157908ba8bd6ac6b16c8e28502953be", null ],
    [ "name", "class_developer\&.html#a0398c537a81a118c0cebd64e453554a8", null ],
    [ "number", "class_developer\&.html#af8a79869e44207cd6d3ef176cff2f2d1", null ],
    [ "salary", "class_developer\&.html#adcd646e88c19d2570f285715076db8bb", null ]
]
.fi
.PP
Definition at line 1 of file class_developer\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
