.TH "MilushYanev_Project2/html/files.js" 3 "Tue Dec 15 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MilushYanev_Project2/html/files.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBfiles\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var files"
\fBInitial value:\fP
.PP
.nf
=
[
    [ "Actor\&.h", "_actor_8h\&.html", "_actor_8h" ],
    [ "BonusPt\&.cpp", "_bonus_pt_8cpp\&.html", null ],
    [ "BonusPt\&.h", "_bonus_pt_8h\&.html", [
      [ "Bonus", "class_bonus\&.html", "class_bonus" ]
    ] ],
    [ "Creator\&.cpp", "_creator_8cpp\&.html", null ],
    [ "Creator\&.h", "_creator_8h\&.html", [
      [ "Creator", "class_creator\&.html", "class_creator" ]
    ] ],
    [ "Developer\&.cpp", "_developer_8cpp\&.html", null ],
    [ "Developer\&.h", "_developer_8h\&.html", [
      [ "Developer", "class_developer\&.html", "class_developer" ]
    ] ],
    [ "GameDate\&.cpp", "_game_date_8cpp\&.html", null ],
    [ "GameDate\&.h", "_game_date_8h\&.html", [
      [ "GameDate", "class_game_date\&.html", "class_game_date" ]
    ] ],
    [ "main\&.cpp", "main_8cpp\&.html", "main_8cpp" ],
    [ "my_NumberT\&.h", "my___number_t_8h\&.html", [
      [ "my_NumberT", "classmy___number_t\&.html", "classmy___number_t" ]
    ] ]
]
.fi
.PP
Definition at line 1 of file files\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
