.TH "MilushYanev_Project2/html/search/functions_9.js" 3 "Tue Dec 15 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MilushYanev_Project2/html/search/functions_9.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.ti -1c
.RI "\fBmain\fP \fBcpp\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBmain\fP cpp"

.PP
Definition at line 3 of file functions_9\&.js\&.
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['playerattack',['playerAttack',['\&.\&./_actor_8h\&.html#a0d2f7982285746f2c3086e8c3430c8aa',1,'playerAttack(Actor &amp;target, Actor &amp;player):&#160
.fi
.PP
Definition at line 1 of file functions_9\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
