.TH "MilushYanev_Project2/html/search/functions_b.js" 3 "Tue Dec 15 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MilushYanev_Project2/html/search/functions_b.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['_7ebonus',['~Bonus',['\&.\&./class_bonus\&.html#ace96cd91925b1f65b2c8596930fed6f5',1,'Bonus']]],
  ['_7ecreator',['~Creator',['\&.\&./class_creator\&.html#af8ecf377073058ea5156afa2e79f901e',1,'Creator']]],
  ['_7edeveloper',['~Developer',['\&.\&./class_developer\&.html#a3a358890cdc55c7c473bbe0865ca0dde',1,'Developer']]],
  ['_7egamedate',['~GameDate',['\&.\&./class_game_date\&.html#a036e058a9f70791d229de1568e1a2c73',1,'GameDate']]]
]
.fi
.PP
Definition at line 1 of file functions_b\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
