.TH "MilushYanev_Project2/html/search/functions_0.js" 3 "Tue Dec 15 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MilushYanev_Project2/html/search/functions_0.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['ai_5fbns',['AI_Bns',['\&.\&./class_bonus\&.html#ae2f51b8407ff820aa8a0a180d2158554',1,'Bonus']]]
]
.fi
.PP
Definition at line 1 of file functions_0\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
