.TH "GameDate" 3 "Tue Dec 15 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameDate \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GameDate\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGameDate\fP ()"
.br
.ti -1c
.RI "\fBGameDate\fP (const \fBGameDate\fP &obj)"
.br
.ti -1c
.RI "\fB~GameDate\fP ()"
.br
.ti -1c
.RI "void \fBsetMonth\fP (int)"
.br
.ti -1c
.RI "void \fBsetDay\fP (int)"
.br
.ti -1c
.RI "void \fBsetYear\fP (int)"
.br
.ti -1c
.RI "int \fBgetDay\fP ()"
.br
.ti -1c
.RI "int \fBgetMonth\fP ()"
.br
.ti -1c
.RI "int \fBgetYear\fP ()"
.br
.ti -1c
.RI "void \fBprint\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBMDY\fP (\fBGameDate\fP *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file GameDate\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GameDate::GameDate ()"

.PP
Definition at line 10 of file GameDate\&.cpp\&.
.SS "GameDate::GameDate (const \fBGameDate\fP & obj)"

.PP
Definition at line 17 of file GameDate\&.cpp\&.
.SS "GameDate::~GameDate ()"

.PP
Definition at line 24 of file GameDate\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "int GameDate::getDay ()"

.PP
Definition at line 43 of file GameDate\&.cpp\&.
.SS "int GameDate::getMonth ()"

.PP
Definition at line 48 of file GameDate\&.cpp\&.
.SS "int GameDate::getYear ()"

.PP
Definition at line 53 of file GameDate\&.cpp\&.
.SS "void GameDate::MDY (\fBGameDate\fP * date)\fC [static]\fP"

.PP
Definition at line 71 of file GameDate\&.cpp\&.
.SS "void GameDate::print ()"

.PP
Definition at line 58 of file GameDate\&.cpp\&.
.SS "void GameDate::setDay (int d)"

.PP
Definition at line 28 of file GameDate\&.cpp\&.
.SS "void GameDate::setMonth (int m)"

.PP
Definition at line 33 of file GameDate\&.cpp\&.
.SS "void GameDate::setYear (int y)"

.PP
Definition at line 38 of file GameDate\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
