.TH "my_NumberT< T >" 3 "Tue Dec 15 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
my_NumberT< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <my_NumberT\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmy_NumberT\fP ()"
.br
.ti -1c
.RI "\fBmy_NumberT\fP (T)"
.br
.ti -1c
.RI "T \fBgetValue\fP ()"
.br
.ti -1c
.RI "void \fBsetValue\fP (T)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>class my_NumberT< T >"

.PP
Definition at line 9 of file my_NumberT\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T > \fBmy_NumberT\fP< T >::\fBmy_NumberT\fP ()"

.PP
Definition at line 40 of file my_NumberT\&.h\&.
.SS "template<class T> \fBmy_NumberT\fP< T >::\fBmy_NumberT\fP (T _value)"

.PP
Definition at line 36 of file my_NumberT\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<class T > T \fBmy_NumberT\fP< T >::getValue ()"

.PP
Definition at line 32 of file my_NumberT\&.h\&.
.SS "template<class T> void \fBmy_NumberT\fP< T >::setValue (T _value)"

.PP
Definition at line 28 of file my_NumberT\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
