.TH "MilushYanev_Project2/html/resize.js" 3 "Tue Dec 15 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MilushYanev_Project2/html/resize.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "function \fBreadCookie\fP (cookie)"
.br
.ti -1c
.RI "function \fBwriteCookie\fP (cookie, val, expiration)"
.br
.ti -1c
.RI "function \fBresizeWidth\fP ()"
.br
.ti -1c
.RI "function \fBrestoreWidth\fP (navWidth)"
.br
.ti -1c
.RI "function \fBresizeHeight\fP ()"
.br
.ti -1c
.RI "function \fBinitResizable\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBcookie_namespace\fP = 'doxygen'"
.br
.ti -1c
.RI "var \fBsidenav\fP"
.br
.ti -1c
.RI "var \fBnavtree\fP"
.br
.ti -1c
.RI "var \fBcontent\fP"
.br
.ti -1c
.RI "var \fBheader\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "function initResizable ()"

.PP
Definition at line 62 of file resize\&.js\&.
.SS "function readCookie ( cookie)"

.PP
Definition at line 4 of file resize\&.js\&.
.SS "function resizeHeight ()"

.PP
Definition at line 52 of file resize\&.js\&.
.SS "function resizeWidth ()"

.PP
Definition at line 37 of file resize\&.js\&.
.SS "function restoreWidth ( navWidth)"

.PP
Definition at line 45 of file resize\&.js\&.
.SS "function writeCookie ( cookie,  val,  expiration)"

.PP
Definition at line 25 of file resize\&.js\&.
.SH "Variable Documentation"
.PP 
.SS "var content"

.PP
Definition at line 2 of file resize\&.js\&.
.SS "var cookie_namespace = 'doxygen'"

.PP
Definition at line 1 of file resize\&.js\&.
.SS "var header"

.PP
Definition at line 2 of file resize\&.js\&.
.SS "var navtree"

.PP
Definition at line 2 of file resize\&.js\&.
.SS "var sidenav"

.PP
Definition at line 2 of file resize\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
