.TH "Actor" 3 "Tue Dec 15 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Actor \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Actor\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBattack\fP"
.br
.ti -1c
.RI "int \fBhealth\fP"
.br
.ti -1c
.RI "string \fBfullName\fP"
.br
.ti -1c
.RI "string \fBclassSelected\fP"
.br
.ti -1c
.RI "int \fBenergy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file Actor\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int Actor::attack"

.PP
Definition at line 9 of file Actor\&.h\&.
.SS "string Actor::classSelected"

.PP
Definition at line 12 of file Actor\&.h\&.
.SS "int Actor::energy"

.PP
Definition at line 13 of file Actor\&.h\&.
.SS "string Actor::fullName"

.PP
Definition at line 11 of file Actor\&.h\&.
.SS "int Actor::health"

.PP
Definition at line 10 of file Actor\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
