.TH "MilushYanev_Project2/Creator.h" 3 "Tue Dec 15 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MilushYanev_Project2/Creator.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'Developer\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCreator\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
