.TH "Developer" 3 "Tue Dec 15 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Developer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Developer\&.h>\fP
.PP
Inherited by \fBCreator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDeveloper\fP ()"
.br
.ti -1c
.RI "\fBDeveloper\fP (string, int, string)"
.br
.ti -1c
.RI "\fBDeveloper\fP (const \fBDeveloper\fP &orig)"
.br
.ti -1c
.RI "\fB~Developer\fP ()"
.br
.ti -1c
.RI "void \fBsetName\fP (string)"
.br
.ti -1c
.RI "void \fBsetNumber\fP (int)"
.br
.ti -1c
.RI "void \fBsetDate\fP (string)"
.br
.ti -1c
.RI "string \fBgetName\fP ()"
.br
.ti -1c
.RI "int \fBgetNumber\fP ()"
.br
.ti -1c
.RI "string \fBgetDate\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string \fBdate\fP"
.br
.ti -1c
.RI "\fBmy_NumberT\fP< int > \fBnumber\fP"
.br
.ti -1c
.RI "\fBmy_NumberT\fP< float > \fBsalary\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file Developer\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Developer::Developer ()"

.PP
Definition at line 5 of file Developer\&.cpp\&.
.SS "Developer::Developer (string n, int num, string d)"

.PP
Definition at line 11 of file Developer\&.cpp\&.
.SS "Developer::Developer (const \fBDeveloper\fP & orig)"

.PP
Definition at line 17 of file Developer\&.cpp\&.
.SS "Developer::~Developer ()"

.PP
Definition at line 21 of file Developer\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "string Developer::getDate ()"

.PP
Definition at line 46 of file Developer\&.cpp\&.
.SS "string Developer::getName ()"

.PP
Definition at line 38 of file Developer\&.cpp\&.
.SS "int Developer::getNumber ()"

.PP
Definition at line 42 of file Developer\&.cpp\&.
.SS "void Developer::setDate (string d)"

.PP
Definition at line 33 of file Developer\&.cpp\&.
.SS "void Developer::setName (string n)"

.PP
Definition at line 25 of file Developer\&.cpp\&.
.SS "void Developer::setNumber (int num)"

.PP
Definition at line 29 of file Developer\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "string Developer::date\fC [protected]\fP"

.PP
Definition at line 12 of file Developer\&.h\&.
.SS "string Developer::name\fC [protected]\fP"

.PP
Definition at line 11 of file Developer\&.h\&.
.SS "\fBmy_NumberT\fP<int> Developer::number\fC [protected]\fP"

.PP
Definition at line 14 of file Developer\&.h\&.
.SS "\fBmy_NumberT\fP<float> Developer::salary\fC [protected]\fP"

.PP
Definition at line 15 of file Developer\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
