.TH "MilushYanev_Project2/html/navtreedata.js" 3 "Tue Dec 15 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MilushYanev_Project2/html/navtreedata.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBNAVTREE\fP"
.br
.ti -1c
.RI "var \fBNAVTREEINDEX\fP"
.br
.ti -1c
.RI "var \fBSYNCONMSG\fP = 'click to disable panel synchronisation'"
.br
.ti -1c
.RI "var \fBSYNCOFFMSG\fP = 'click to enable panel synchronisation'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var NAVTREE"
\fBInitial value:\fP
.PP
.nf
=
[
  [ "My Project", "index\&.html", ]
]
.fi
.PP
Definition at line 1 of file navtreedata\&.js\&.
.SS "var NAVTREEINDEX"
\fBInitial value:\fP
.PP
.nf
=
[
"index\&.html"
]
.fi
.PP
Definition at line 6 of file navtreedata\&.js\&.
.SS "var SYNCOFFMSG = 'click to enable panel synchronisation'"

.PP
Definition at line 12 of file navtreedata\&.js\&.
.SS "var SYNCONMSG = 'click to disable panel synchronisation'"

.PP
Definition at line 11 of file navtreedata\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
