.TH "MilushYanev_Project2/html/search/searchdata.js" 3 "Tue Dec 15 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MilushYanev_Project2/html/search/searchdata.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBindexSectionsWithContent\fP"
.br
.ti -1c
.RI "var \fBindexSectionNames\fP"
.br
.ti -1c
.RI "var \fBindexSectionLabels\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var indexSectionLabels"
\fBInitial value:\fP
.PP
.nf
=
{
}
.fi
.PP
Definition at line 9 of file searchdata\&.js\&.
.SS "var indexSectionNames"
\fBInitial value:\fP
.PP
.nf
=
{
}
.fi
.PP
Definition at line 5 of file searchdata\&.js\&.
.SS "var indexSectionsWithContent"
\fBInitial value:\fP
.PP
.nf
=
{
}
.fi
.PP
Definition at line 1 of file searchdata\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
